S = RECORD (EOL RECORD)* (EOL PARTIAL_RECORD)? EOL?

RECORD = FIELD (TAB FIELD)+

PARTIAL_RECORD = (FIELD TAB)* PARTIAL_FIELD

FIELD = ESCAPED | NON_ESCAPED

PARTIAL_FIELD = PARTIAL_ESCAPED | NON_ESCAPED

PARTIAL_ESCAPED = DQUOTE (TEXTDATA | EOL | TAB | ESCAPED_DQUOTE )*

ESCAPED = DQUOTE (TEXTDATA | EOL | TAB | ESCAPED_DQUOTE )* DQUOTE

NON_ESCAPED = TEXTDATA*

TAB = #"\t"

DQUOTE = #'"'

ESCAPED_DQUOTE = #'""'

TEXTDATA = #'[^\t\r\n"]+'

EOL = #"(?:\r\n|\r|\n)"
