-- Adds the RNA seq for SRA template
-- For the definition, see
-- https://docs.google.com/spreadsheets/d/1366FPVIjJUK6bTIJWW1ohAhGOy3ro-WFMRG5PYnZLko/edit#gid=0


INSERT INTO metadata_templates(id, name) VALUES ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', 'RNA for SRA');


INSERT INTO metadata_attributes(id, name, description, required, value_type_id) VALUES
  ('e186515e-6f30-4a8a-89a5-59e086d2d402',
   'bioproject_accession',
   'typically of the form `PRJN[num]`, NOT `SUB[num]`',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('9044f3b5-2fb5-42a0-8ad1-8ecfe5f0c860',
   'biosample_accession',
   'typically of the form `SAMN[num]`, NOT `SUB[num]`',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('544731b5-a00d-42e9-acf2-9b60a26c6452',
   'sample_name',
   '`sample_name` as described for the Biosample',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('2a18dbfd-fef4-4b9f-a167-92ab65999533',
   'library_ID',
   'This should be a short unique identifier for the sequencing library. Each `library_ID` MUST be unique.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('1fb008a3-7934-4de4-94b7-7efa29129876',
   'title/short description',
   'This should be a short description that will identify the dataset on public pages. A clear and concise formula for the title would be: {methodology} of {organism): {sample info}. For example: RNA of Mus muscalus: adult spleen.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('846c527e-d36a-459c-98cd-aea7cdb63744',
   'library_strategy',
   'Choose from controlled vocabulary.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('44a2b2b8-d838-4dfa-b945-60e2ed594cfb',
   'library_source',
   'Choose from controlled vocabulary.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('c00e502e-4f26-4303-93d9-22a08964979e',
   'library_selection',
   'Choose FROM controlled vocabulary.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('600ef58e-42cc-46c6-9db0-097a62c2f011',
   'library_layout',
   '`paired-end` or `single`',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('fc08ff9b-2588-4946-b489-ca7ab64ed143',
   'platform',
   'Choose from controlled vocabulary.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('10d47d30-8fe4-4241-a2dc-142d5edc9641',
   'instrument_model',
   'Choose from controlled vocabulary.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('936888ff-1214-4ca6-b901-5c55d72160b6',
   'design_description',
   'free form description of the methods used to create the sequencing library; a brief "materials and methods" section',
   TRUE,
   '127036FF-EF19-4665-A9A9-7A6878D9813A'),

  ('ee98285c-f834-4560-8893-c232c307b920',
   'reference_genome_assembly',
   'Please include NCBI assembly name or accession number.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('02f47367-a739-419a-b18d-5ffe70d78484',
   'alignment_software',
   'Please include version # if known.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('1d5db775-dc66-4660-8612-80cbe4ca2ad7',
   'forward_read_length',
   'forward read in a paired library',
   TRUE,
   'C6CB42CD-7C47-47A1-8704-F6582B510ACF'),

  ('d02818cd-67cd-41ed-8bb3-253393e8d211',
   'reverse_read_length',
   'paired only',
   TRUE,
   'C6CB42CD-7C47-47A1-8704-F6582B510ACF'),

  ('9e2fcc28-713b-4125-b5eb-ba1e0be20c83',
   'filetype',
   'This is the format of the data to be submitted. It must be one of the types in the list.',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('2374e3e2-9cd7-47e7-826b-5d2bb85dfb54',
   'filename',
   'file name including all extensions, but NOT path information',
   TRUE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6'),

  ('8d049637-2617-4f32-b2c6-8fc4bc986db1',
   'MD5_checksum',
   'We will not be generating this yet. This is the checksum generated by the MD5 algorithm for the indicated file.',
   FALSE,
   'C29B0B10-D660-4582-9EB7-40C4F1699DD6');


INSERT INTO metadata_template_attrs(template_id, attribute_id, display_order) VALUES
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', 'e186515e-6f30-4a8a-89a5-59e086d2d402', 0),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '9044f3b5-2fb5-42a0-8ad1-8ecfe5f0c860', 1),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '544731b5-a00d-42e9-acf2-9b60a26c6452', 2),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '2a18dbfd-fef4-4b9f-a167-92ab65999533', 3),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '1fb008a3-7934-4de4-94b7-7efa29129876', 4),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '846c527e-d36a-459c-98cd-aea7cdb63744', 5),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '44a2b2b8-d838-4dfa-b945-60e2ed594cfb', 6),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', 'c00e502e-4f26-4303-93d9-22a08964979e', 7),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '600ef58e-42cc-46c6-9db0-097a62c2f011', 8),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', 'fc08ff9b-2588-4946-b489-ca7ab64ed143', 9),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '10d47d30-8fe4-4241-a2dc-142d5edc9641', 10),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '936888ff-1214-4ca6-b901-5c55d72160b6', 11),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', 'ee98285c-f834-4560-8893-c232c307b920', 12),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '02f47367-a739-419a-b18d-5ffe70d78484', 13),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '1d5db775-dc66-4660-8612-80cbe4ca2ad7', 14),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', 'd02818cd-67cd-41ed-8bb3-253393e8d211', 15),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '9e2fcc28-713b-4125-b5eb-ba1e0be20c83', 16),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '2374e3e2-9cd7-47e7-826b-5d2bb85dfb54', 17),
  ('c52b1a0c-0fbd-4120-b107-92154dfbe2dc', '8d049637-2617-4f32-b2c6-8fc4bc986db1', 18);
