FROM discoenv/facepalm:dev

COPY setup-dev-database.sh /bin/setup-dev-database.sh
COPY update-dev-database.sh /bin/update-dev-database.sh
COPY facepalm-standalone.jar /facepalm-standalone.jar

CMD ["setup-dev-database.sh"]
