#!/bin/bash

# Taken from a comment on the docker hub.

cat > /var/lib/postgresql/data/pg_hba.conf <<EOF
# Generated by fix-acl.sh
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     trust

# Allow anyone to connect remotely so long as they have a valid
# username and 
# password.
host all all 0.0.0.0/0 md5
EOF
